<?php

namespace FacturaScripts\Plugins\SolwedPlugins\Lib;

use FacturaScripts\Core\Tools;
use FacturaScripts\Core\Http;

class SolwedGitHubPlugins
{
    /** @var string */
    private $githubUsername;

    /** @var array */
    private $plugins = [];

    public function __construct()
    {
        //$this->githubUsername = Tools::settings('pluginportal', 'github_username', '');
        $this->githubUsername = "SolWed-es";
        $this->loadPlugins();
    }

    public function getPlugins(): array
    {
        return $this->plugins;
    }

    public function getPluginInfo(string $pluginName): ?array
    {
        foreach ($this->plugins as $plugin) {
            if ($plugin['name'] === $pluginName) {
                return $plugin;
            }
        }

        return null;
    }

    public function getDownloadUrl(array $pluginInfo): string
    {
        return "https://github.com/{$this->githubUsername}/{$pluginInfo['name']}/archive/refs/heads/main.zip";
    }

    public function downloadPlugin(string $url, string $destination): bool
    {
        $content = Http::get($url)->setTimeout(30)->getContent();
        if (empty($content)) {
            return false;
        }

        return file_put_contents($destination, $content) !== false;
    }

    private function loadPlugins(): void
    {
        if (empty($this->githubUsername)) {
            Tools::log()->error('github-username-not-configured');
            return;
        }

        // Dummy data
        // todo: fetch this from a JSON file, ideally auto-generated by Github actions

        $this->plugins = [
            [
                'name' => 'AdvancedInvoices',
                'description' => 'Enhanced invoice management with additional fields',
                'version' => 1.2,
                'health' => 5
            ],
            [
                'name' => 'ClientPortal',
                'description' => 'Client self-service portal for order tracking',
                'version' => 2.1,
                'health' => 4
            ],
            [
                'name' => 'InventoryManager',
                'description' => 'Advanced inventory management with barcode support',
                'version' => 1.5,
                'health' => 5
            ]
        ];
    }
}
