name: Update Plugin List

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-plugin-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate plugin list
        run: |
          php .github/scripts/generate-plugin-list.php

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add plugin-list.json
          git diff --staged --quiet || git commit -m "Update plugin list"
          git push